name: Test PyPI Publishing

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '.github/workflows/test-pypi.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Test package installation
      run: |
        pip install dist/*.whl
        venvoy --help
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-dist
        path: dist/

  test-publish:
    needs: test-build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
    environment: test-pypi
    permissions:
      id-token: write  # For trusted publishing
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: test-dist
        path: dist/
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true 